module.exports = {
  darkMode: ["class"],
  content: [
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "./pages/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        satoshi: ['var(--font-satoshi)', 'Satoshi', 'system-ui', 'sans-serif'],
        sans: ['var(--font-geist)', 'Geist', 'system-ui', 'sans-serif'],
        serif: ['var(--font-instrument-serif)', 'Instrument Serif', 'Georgia', 'serif'],
        mono: ['var(--font-dm-mono)', 'DM Mono', 'SFMono-Regular', 'monospace'],
        display: ['var(--font-instrument-serif)', 'Instrument Serif', 'Georgia', 'serif'],
      },
      colors: {
        'electric-cyan': '#19d0e8',
        'sky-signal': '#44ccff',
        'deep-teal': '#062f34',
        'void-black': '#000000',
        'obsidian': '#010101',
        'midnight-surface': '#191919',
        'graphite': '#282828',
        'charcoal': '#363636',
        'slate-custom': '#3f3f3f',
        'steel-gray': '#7f7f7f',
        'paper-white': '#ffffff',
        'ghost-gray': '#c0c0c0',
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background, 0 0% 10%))',
          foreground: 'hsl(var(--sidebar-foreground, 0 0% 96%))',
          primary: 'hsl(var(--sidebar-primary, 0 0% 10%))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground, 0 0% 100%))',
          accent: 'hsl(var(--sidebar-accent, 0 0% 16%))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground, 0 0% 96%))',
          border: 'hsl(var(--sidebar-border, 0 0% 16%))',
          ring: 'hsl(var(--sidebar-ring, 187 82% 50%))',
        },
      },
      borderRadius: {
        'cards': '18px',
        'buttons': '100000px',
        'tags': '100000px',
        'album-art': '12px',
        'player-bar': '18px',
      },
      spacing: {
        'section-gap': '80px',
        'card-padding': '24px',
        'element-gap': '10px',
      },
      maxWidth: {
        'page': '1200px',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
