import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import BeamsBackground from "@/components/Background";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
<Providers>
{/* <BeamsBackground intensity="strong"> */}
{children}
{/* </BeamsBackground> */}
</Providers>
      </body>
    </html>
  );
}
